version: '3.7'
services:
  db:
    build:
      context: docker/config
      dockerfile: mysql.dockerfile
    image: mysql_db
    container_name: mysql_laravel_service_1
    restart: unless-stopped
    ports:
      - "4306:3306"
    volumes:
      - dbdata:/var/lib/mysql:rw
    networks:
      - lumen_laravel

  app:
    build:
      context: docker/config
      dockerfile: php.dockerfile
    image: lumen_php_laravel_app
    depends_on:
      - db
    container_name: lumen_laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
#    command: ["./wait-for-mysql.sh", "php", "fpm"]
    networks:
      - lumen_laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_service
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - app
      - db
    networks:
      - lumen_laravel

volumes:
  dbdata:
    driver: local

networks:
  lumen_laravel:
    driver: bridge
